### ISSUE TITLE
Typo in master schema

### ISSUE THREAD

**Issue by davidmegginson** [OCHA-DAP/tools-datacheck-validation#1]
validation-schema.json has "#value_required" instead of "#valid_required" — that's why it was failing, while the Google Docs schema at https://docs.google.com/spreadsheets/d/1EyUzGO7M2juKyVuY2p1nPcxM29SauV1kT2vjRBnS9wU/edit#gid=0 was not.

Will issue a PR.

**Comment by danmihaila** [comment]
@davidmegginson we need to fix the documentation here - https://docs.google.com/document/d/1d-jQJXvlXsEkTAF-MJLeuO6DY69ssCbqEkCvVyCb9d0/edit# . We got the sample from there.
